name: Test running tests
run-name: Testing if test workflow works
on:
  push:
    branches:
      - trying_tools
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Step 3: Install dependencies 
      - name: Install dependencies
        run: npm install

      # Step 4: Run Jest tests with coverage
      - name: Run Jest tests
        run: npm test -- --json --outputFile=test-results.json
        continue-on-error: true
        
      # Step 5: Create issue if failing testsuite found
      - name: Create an issue if tests fail
        run: |
          failed_cases=$(jq -r '.testResults[] | select(.status == "failed") | {suite: .name, failed_tests: [.assertionResults[] | select(.status == "failed") | {test_name: .fullName}]} ' test-results.json)'
          echo "$failed_cases" | while IFS= read -r case; do
          
            suite_name=$(echo "$case" | jq -r '.suite')
            test_name=$(echo "$case" | jq -r '.failed_tests.test_name')

            ISSUE_TITLE="Failure in $suite_name - $test_name"
            ISSUE_BODY="**Test Suite**: $suite_name\n**Test Case**: $test_name\n"
          done
      # Step 5: Generate Coveralls report
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
