name: Test running tests
run-name: Testing if test workflow works
on:
  push:
    branches:
      - trying_tools
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Step 3: Install dependencies 
      - name: Install dependencies
        run: npm install

      # Step 4: Run Jest tests with coverage
      - name: Run Jest tests
        run: npm test -- --json --outputFile=test-results.json
        continue-on-error: true 

      # Step 5: Create issue if failing testsuite found
      - name: Create an issue if tests fail
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          failed_cases=$(jq -c -r '.testResults[] as $suite | select(.status == "failed") | .assertionResults[] | select(.status == "failed") | {file: $suite.name, suite: .ancestorTitles | join(" > "), test_name: .title}' test-results.json)
            
          if [ -z "$failed_cases" ]; then
            echo "No failed tests"
            exit 0
          fi

          echo "$failed_cases"

          done
